Main.o: Main.cpp ShaderProgram.h Mesh.h Camera.h

ShaderProgram.h:

Mesh.h:

Camera.h:
ShaderProgram.o: ShaderProgram.cpp ShaderProgram.h

ShaderProgram.h:
Mesh.o: Mesh.cpp Mesh.h ShaderProgram.h

Mesh.h:

ShaderProgram.h:
Camera.o: Camera.cpp Camera.h

Camera.h:
